apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Register ECR Binary

on:
  workflow_dispatch:

jobs:
  register:
    steps:
      - name: Register Build Artifact
        uses: cloudbees-io/register-build-artifact@v2
        with:
          name: vulnerable-image
          version: "0.1"
          url: 020229604682.dkr.ecr.us-east-1.amazonaws.com/throwaway/actions/vulnerable-image:Tag1